name: Lint on PR

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    name: lint
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint
